# Generated by Django 3.2.18 on 2023-04-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('toys', 'Toys'), ('technology', 'Technology'), ('sports', 'Sports'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('household', 'Household'), ('homeware', 'Homeware'), ('other', 'Other')], default='food', max_length=50),
        ),
    ]
